# Generated by Django 5.0.6 on 2026-05-21 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Org",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("website_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("stack_tags", models.JSONField(default=list)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.SlugField(unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("stipend_min_usd", models.PositiveIntegerField(blank=True, null=True)),
                ("stipend_max_usd", models.PositiveIntegerField(blank=True, null=True)),
                ("stipend_inr", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "USD"), ("INR", "INR")],
                        default="USD",
                        max_length=3,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("website_url", models.URLField(blank=True)),
                ("deadline_opens_at", models.DateTimeField(blank=True, null=True)),
                ("deadline_closes_at", models.DateTimeField(blank=True, null=True)),
                ("slots_count", models.PositiveIntegerField(blank=True, null=True)),
                ("acceptance_rate", models.FloatField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("accent", "accent"),
                            ("warn", "warn"),
                            ("muted", "muted"),
                        ],
                        default="accent",
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ProgramOrg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="warroom.org"
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warroom.program",
                    ),
                ),
            ],
            options={
                "unique_together": {("program", "org", "year")},
            },
        ),
        migrations.AddField(
            model_name="org",
            name="programs",
            field=models.ManyToManyField(
                blank=True,
                related_name="orgs",
                through="warroom.ProgramOrg",
                to="warroom.program",
            ),
        ),
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("content_markdown", models.TextField(blank=True)),
                ("version", models.PositiveSmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "draft"),
                            ("submitted", "submitted"),
                            ("accepted", "accepted"),
                            ("rejected", "rejected"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                ("mentor_feedback", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="warroom.org"
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warroom.program",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProgramTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("tracking", "tracking"),
                            ("applied", "applied"),
                            ("accepted", "accepted"),
                            ("rejected", "rejected"),
                        ],
                        default="tracking",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("orgs", models.ManyToManyField(blank=True, to="warroom.org")),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warroom.program",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_tracking",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "program")},
            },
        ),
    ]
