# Generated by Django 5.0.6 on 2026-05-27 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField(help_text='markdown')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='warroom.program')),
            ],
            options={
                'verbose_name': 'Contest FAQ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContestFlowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='markdown')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_steps', to='warroom.program')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContestOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_long', models.TextField(blank=True, help_text='markdown · full description')),
                ('objective', models.TextField(blank=True, help_text='markdown')),
                ('eligibility', models.TextField(blank=True, help_text='markdown')),
                ('registration_process', models.TextField(blank=True, help_text='markdown')),
                ('prerequisites', models.TextField(blank=True, help_text='markdown')),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='overview', to='warroom.program')),
            ],
        ),
        migrations.CreateModel(
            name='ContestTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "2026 timeline"', max_length=120)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True, help_text='shown first / by default')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to='warroom.program')),
            ],
            options={
                'ordering': ['-is_current', '-year', 'order'],
            },
        ),
        migrations.CreateModel(
            name='OverviewLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('url', models.URLField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='warroom.program')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StipendPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "phase 1 — midterm"', max_length=120)),
                ('timing', models.CharField(blank=True, help_text='e.g. "after midterm evaluation"', max_length=120)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stipend_phases', to='warroom.program')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StipendTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, help_text='country / region, blank = global', max_length=120)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('INR', 'INR')], default='USD', max_length=3)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stipend_tiers', to='warroom.program')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('link_url', models.URLField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='warroom.contesttimeline')),
            ],
            options={
                'ordering': ['order', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='VideoTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_topics', to='warroom.program')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('program', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, help_text='markdown')),
                ('gdrive_url', models.URLField(help_text='google drive share link')),
                ('thumbnail_url', models.URLField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='warroom.videotopic')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('topic', 'slug')},
            },
        ),
    ]
